[book]
authors = ["trantorian"]
language = "en"
multilingual = false
src = "src"
title = "Blockchain from scratch"

[preprocessor]

[preprocessor.mermaid]
command = "mdbook-mermaid"

[output]

[output.html]
additional-js = ["mermaid.min.js", "mermaid-init.js"]
git-repository-url = "https://github.com/Trantorian1/notes-rust-blockchain/"
mathjax-support = true
